name: Generate release
on:
  workflow_call:
    inputs:
      draft:
        required: true
        type: boolean
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true

permissions: {}
jobs:
  generate-release:
    uses: ./.github/workflows/generate-release.yaml
    permissions: {}
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
    with:
      DRAFT: ${{inputs.draft}}