name: Generate release
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions: {}
jobs:
  generate-release:
    uses: ./.github/workflows/wc-generate-release.yaml
    permissions:
      issues: write
    if: |
      github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    with:
      draft: true
      app_id_url: "op://Github/uhto3hzapjcxicwm664wvh4zu4/AppID"
      app_secret_url: "op://Github/uhto3hzapjcxicwm664wvh4zu4/private_key"
    secrets:
      op_service_account_token: ${{secrets.OP_SERVICE_ACCOUNT_TOKEN}}