---
name: test
on: pull_request
permissions: {}
jobs:
  auto-add-label:
    uses: ./.github/workflows/wc-auto-add-label.yaml
    permissions: {}
    if: |
      github.event.pull_request.user.login != 'renovate[bot]'
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}