---
name: test
on: pull_request
permissions: {}
jobs:
  auto-add-label:
    uses: ./.github/workflows/wc-auto-add-label.yaml
    permissions: {}
    if: >-
      github.event.pull_request.user.login != 'renovate[bot]' &&
      contains(fromJSON('["feat", "fix", "test", "doc"]'), github.head_ref)
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
  
  path-filter:
    outputs:
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            ghalint:
              - .github/workflows/*.yaml
              - aqua/aqua.yaml
              - aqua/imports/ghalint.yaml
              - ghalint.yaml
  
  ghalint:
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    uses: ./.github/workflows/wc-ghalint.yaml
    permissions: {}

  status-check:
    needs:
      - ghalint
    if: failure()
    uses: ./.github/workflows/wc-status-check.yaml
    permissions: {}

  enable-automerge:
    needs:
      - status-check
    # "! failure() && ! cancelled()" is required. success() returns false if dependent jobs are skipped.
    # https://github.com/community/community/discussions/45058
    # By default success() is used so we have to override success() by "! failure() && ! cancelled()"
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    uses: ./.github/workflows/wc-enable-auto-merge.yaml
    permissions:
      contents: write # For enable automerge
      pull-requests: write # For enable automerge
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}