name: bump-version
on: 
  workflow_call:
    inputs:
      changelog:
        required: true
        type: string
      major_title:
        description: "Titles that fall under major version upgrades. e.g. ## ⚠️ Breaking Changes"
        required: true
        type: string
      minor_title:
        description: "Titles that fall under minor version upgrades. e.g. ## Features"
        required: true
        type: string
    outputs:
      RELEASE_VERSION:
        description: "Next release version name determined automatically"
        value: ${{jobs.bump-version.outputs.RELEASE_VERSION}}
permissions: {}
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions: {}
    if: success()
    outputs:
      RELEASE_VERSION: ${{steps.set-version.outputs.RELEASE_VERSION}}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.8.0
      - name: Check bump level
        run: |
          set -eu
          changelog=$(echo "${{inputs.changelog}}" | sed 's/\\/\\\\/g')
          search_features="${{inputs.minor_title}}"
          search_breaking_changes="${{inputs.major_title}}"

          if [[ "$changelog" == *"$search_features"* ]]; then
              release_level="minor"
          elif [[ "$changelog" == *"$search_breaking_changes"* ]]; then
              release_level="major"
          else
              release_level="patch"
          fi

          echo "level=$release_level" >> $GITHUB_ENV
      - name: Set release version for output.
        id: set-version
        run: |
          svu
          next_version=$(svu $level)
          echo "RELEASE_VERSION=$next_version" >> $GITHUB_OUTPUT
          echo "::notice::Next release is $level update, version $next_version"