name: Generate release workflow
on:
  workflow_call:
    inputs:
      draft:
        required: true
        default: false
        type: boolean
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true

permissions: {}
jobs:
  generate-pull-request:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
      - name: Set current datetime
        id: datetime
        run: echo "CURRENT_DATETIME=$(date +"%Y-%m-%dT%H:%M:%S%z")" >> $GITHUB_OUTPUT
        env:
          TZ: 'Asia/Tokyo'
      - name: Generate pull request
        run: |
          set -eu

          draft_option=''
          if [ ${{inputs.draft}} = true ]; then
            draft_option+='--draft'
          fi
          
          gh release create "${HEAD_REF#release/}" \
            --notes "${BODY//\\/\\\\}" \
            --target ${{github.sha}} \
            --title "${HEAD_REF#release/}" \
            $draft_option
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
          HEAD_REF: ${{github.event.pull_request.head.ref}}
          BODY: |-
            ${{github.event.pull_request.body}}
            > **Note**
            > This release was published on ${{steps.datetime.outputs.CURRENT_DATETIME}}

            > **Note**
            > Commit SHA is ${{github.sha}}
  close-milestone:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close milestone
        run: |
          set -eu

          milestones=$(gh api -X GET /repos/${{github.repository}}/milestones -f state=all)
          milestone_number=$(echo "${milestones}" | jq ". | map(select(.title == \"${HEAD_REF#release/}\")) | first | .number")
          gh api -X PATCH repos/${{github.repository}}/milestones/${milestone_number} -f state=close
        env:
          GITHUB_TOKEN: ${{github.token}}
          HEAD_REF: ${{github.event.pull_request.head.ref}}